In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math

In [10]:
df= pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

**Handling Missing Value**

In [11]:
bd_median= math.floor(df.bedrooms.median())
bd_median

4

In [12]:
df.bedrooms = df.bedrooms.fillna(bd_median)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
reg= linear_model.LinearRegression() # creating object of linearRegression Class
reg.fit(df[["area",'bedrooms','age']],df.price) #Training model with traning set 
#fit(df[['Independent variables']],df.dependent_varibale)

LinearRegression()

In [16]:
reg.predict(np.array([[3200,4.0,18]]))

array([615307.4140366])

**The price we predicted is nealry equal to price in training set, lets try by chanhing the age for the same set, thats is what if the house is 225 yrs old instead of 18 then**

In [21]:
reg.predict(np.array([[3200,4.0,25]]))

array([592685.38867617])

In [22]:
reg.coef_
#[m1,m2,m3]

array([  112.06244194, 23388.88007794, -3231.71790863])

In [23]:
reg.intercept_
#b

221323.00186540408